### ISSUE TITLE
Can run in webwork?

### ISSUE THREAD

**Issue by f5cs** [apache/cordova-js#202]
# Feature Request
Can it run in webwork?

## Motivation Behind Feature

JS engine is single-threaded, if a large number of time-consuming complex operations will make UI pause, such as reading and writing files, operating database, which will lead to poor user experience. So we hope to put these operations into the underlying thread (web work) to ensure that users operate smoothly.

## Feature Description
ordova JS uses many main variables such as windows, which makes it impossible to use them in Web work (in this case, the main variable is self). Can you decide whether to use windows or self according to your judgment?

## Alternatives or Workarounds

I am currently rewriting the code manually, but I lose all of this work every time I upgrade.

**Comment by dpogue** [comment]
No, Cordova cannot run in a web worker because the techniques that we use to communicate between the web page and the native code aren't available using the APIs in web workers.

However, all Cordova commands are asynchronous, and the code on the native side should be making use of thread pools to avoid blocking.
